apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
        - name: kafka
          image: "enmasseproject/kafka-inmemory:latest"
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
          command:
            - ./kafka_run.sh
          volumeMounts:
            - name: kafka-storage
              mountPath: /tmp/kafka/
          lifecycle:
            preStop:
              exec:
                command:
                  - ./bin/kafka-server-stop.sh
          livenessProbe:
              tcpSocket:
                port: kafka
      volumes:
        - name: kafka-storage
          emptyDir: {}
